import datetime
from typing import Optional

from sqlmodel import Field, SQLModel

class Meme(SQLModel, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
    filename: str = Field(index=True, unique=True)
    category: Optional[str] = None
    description: Optional[str] = None
    keywords: Optional[str] = None
    text_in_image: Optional[str] = None
    source_url: Optional[str] = None
    status: str = Field(default="pending", index=True)
    attempts: int = Field(default=0)
    last_error: Optional[str] = None
    last_attempt_at: Optional[datetime.datetime] = None
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc), index=True)
    updated_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))
    
    phash: Optional[str] = Field(default=None, index=True)
    
    is_false_positive: bool = Field(default=False)


class Duplicate(SQLModel, table=True):
    """Represents a duplicate link between two files.

    `is_false_positive` marks that this specific duplicate link
    should be ignored when forming duplicate groups.
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    filename_a: str = Field(index=True)
    filename_b: str = Field(index=True)
    is_false_positive: bool = Field(default=False, index=True)
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


class DuplicateGroup(SQLModel, table=True):
    """Represents a detected group of visually similar memes."""
    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


class MemeDuplicateGroup(SQLModel, table=True):
    """Association table linking memes to duplicate groups.

    We store `filename` to avoid strict foreign key dependencies on numeric IDs,
    and keep it simple to insert/delete rows.
    """
    id: Optional[int] = Field(default=None, primary_key=True)
    group_id: int = Field(index=True)
    filename: str = Field(index=True)
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))


class UserToken(SQLModel, table=True):
    """API token for user authentication (generated by logged-in user)."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: str = Field(index=True)
    name: str
    token_hash: str
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc), index=True)
    last_used_at: Optional[datetime.datetime] = None
    expires_at: Optional[datetime.datetime] = None
    revoked: bool = Field(default=False, index=True)


class BasicAuthUser(SQLModel, table=True):
    """Basic Auth user credentials table."""
    id: Optional[int] = Field(default=None, primary_key=True)
    username: str = Field(index=True, unique=True)
    password_hash: str
    enabled: bool = Field(default=True, index=True)
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))
    last_used_at: Optional[datetime.datetime] = None
    failed_attempts: int = Field(default=0)
    locked_until: Optional[datetime.datetime] = None


class FileShareToken(SQLModel, table=True):
    """Temporary share token for accessing a specific file."""
    id: Optional[int] = Field(default=None, primary_key=True)
    filename: str = Field(index=True)
    token_hash: str
    created_by: str = Field(index=True)
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc))
    expires_at: datetime.datetime = Field(index=True)
    used_count: int = Field(default=0)


class TokenResponse(SQLModel):
    """Response when generating a new token (token shown only once)."""
    id: int
    name: str
    token: str  # Plain JWT - shown only once!
    created_at: datetime.datetime


class TokenInfo(SQLModel):
    """Token info in list (without the actual token)."""
    id: int
    name: str
    created_at: datetime.datetime
    last_used_at: Optional[datetime.datetime]
    expires_at: Optional[datetime.datetime]
    revoked: bool
    expired: bool


class ShareTokenInfo(SQLModel):
    """Info about a shared file token."""
    id: int
    filename: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    used_count: int


class UserInfo(SQLModel):
    """Current authenticated user info."""
    user_id: str
    name: Optional[str]
    email: Optional[str]
    picture: Optional[str]


class AuditLog(SQLModel, table=True):
    """Audit log for sensitive actions (DELETE, PATCH, POST state-changing operations)."""
    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: str = Field(index=True)  # User who performed the action (OIDC sub or username)
    username: Optional[str] = Field(default=None, index=True)  # Human-readable username from OIDC preferred_username
    action: str = Field(index=True)  # e.g., "DELETE_MEME", "MERGE_DUPLICATES", "PATCH_MEME"
    resource: Optional[str] = Field(default=None, index=True)  # e.g., filename, group_id, etc. (optional for actions without specific resource)
    resource_type: str = Field(default="meme")  # Type of resource (meme, group, token, etc.)
    details: Optional[str] = None  # Additional context (JSON string)
    timestamp: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc), index=True)
    ip_address: Optional[str] = None  # IP address of the request
    status: str = Field(default="success")  # "success", "failure", etc.


class DownloadJob(SQLModel, table=True):
    """Track video download jobs from URLs using yt-dlp."""
    id: Optional[int] = Field(default=None, primary_key=True)
    url: str = Field(index=True)  # Original video URL
    user_id: str = Field(index=True)  # User who created the job
    status: str = Field(default="pending", index=True)  # pending, downloading, processing, completed, failed
    progress_percent: float = Field(default=0.0)  # 0.0 to 100.0
    filename: Optional[str] = None  # Final filename on WebDAV (NULL until uploaded)
    error_message: Optional[str] = None  # Error details if failed
    created_at: datetime.datetime = Field(default_factory=lambda: datetime.datetime.now(datetime.timezone.utc), index=True)
    started_at: Optional[datetime.datetime] = None  # Download start time
    completed_at: Optional[datetime.datetime] = None  # Completion timestamp
    video_title: Optional[str] = None  # Video title from metadata
    video_duration: Optional[int] = None  # Duration in seconds
    file_size_bytes: Optional[int] = None  # Final file size

